version: "3.3"

services:

  db:
    container_name: "hermes-mysql"
    image: "mysql:5.7"
    volumes:
      - "hermes-mysql-data:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak # Create an empty keycloak schema
    restart: unless-stopped

  keycloak:
    container_name: "hermes-keycloak"
    depends_on: 
      - db
    image: "europe-west2-docker.pkg.dev/hua-hermes/keycloak/prod:5414f5f"
    # Both internal and external requests are being made to keycloak. So URL must be the same for both cases
    # Change the HTTP port to 80 to make the alias truly work
    command: ["-b 0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/hermes-export-dev.json", "-Dkeycloak.migration.strategy=IGNORE_EXISTING", "-Djboss.http.port=80"]
    networks: 
      default:
        aliases: 
          - sso.hermes.local
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: hermes-mysql
      DB_VENDOR: mysql
      DB_USER: root
      DB_PASSWORD: root
    restart: unless-stopped

  backend:
    container_name: "hermes-backend"
    depends_on: 
      - db
      - keycloak
    image: "europe-west2-docker.pkg.dev/hua-hermes/back-end/prod:4ca9b8f"
    environment:
      DB_URL: hermes-mysql
      DB_SCHEMA: hermes
      DB_USER: root
      DB_PASS: root
      KEYCLOAK_AUTH_SERVER_URL: http://sso.hermes.local/auth
      KEYCLOAK_CREDENTIALS_SECRET: 81f7d18a-b8b6-4ff9-86b1-ce6e18cb097b
    restart: unless-stopped

  intenal-frontend:
    container_name: "hermes-internal-frontend"
    depends_on:
      - db
      - keycloak
      - backend
    image: "europe-west2-docker.pkg.dev/hua-hermes/internal-front-end/prod:7fcd6c2"
    environment:
      KEYCLOAK_AUTH_SERVER_URL: http://sso.hermes.local/auth
      KEYCLOAK_CREDENTIALS_SECRET: 9855054d-647a-426b-902c-9d9f539027bf
      KEYCLOAK_ADMIN_CLIENTID: keycloak-admin
      KEYCLOAK_ADMIN_CLIENTSECRET: 71ff7d46-ad8f-4b52-8107-00415c07f0d4
      HERMES_BACKEND_URL: http://hermes-backend:8080
    restart: unless-stopped  

  external-frontend:
    container_name: "hermes-external-frontend"
    depends_on:
      - db
      - keycloak
      - backend
    image: "europe-west2-docker.pkg.dev/hua-hermes/external-front-end/prod:f77f051"
    environment:
      KEYCLOAK_AUTH_SERVER_URL: http://sso.hermes.local/auth
      KEYCLOAK_CREDENTIALS_SECRET: 81aac51a-17cf-4bff-8983-97f90403ee0a
      KEYCLOAK_ADMIN_CLIENTID: keycloak-admin
      KEYCLOAK_ADMIN_CLIENTSECRET: 71ff7d46-ad8f-4b52-8107-00415c07f0d4
      HERMES_BACKEND_URL: http://hermes-backend:8080
    restart: unless-stopped  
    
  nginx: 
    container_name: hermes-nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped  
  
  mailhog:
    container_name: "hermes-mailhog"
    image: "mailhog/mailhog:v1.0.1"
    restart: unless-stopped

volumes:
  hermes-mysql-data:
